### ISSUE TITLE
No wifi after use a antenna 

### ISSUE THREAD

**Issue by laarhoven1** [NoobishSVK/TEF6686-remastered#2]
I buy a wifi antenna for the tef6686 now i got wifi signaal icon in the settings i change the credentials for my wifi network.
On the router in not getting Anny ip adres from my dhcp server.
192.168.178.1
Only the Mac adres is visible on the router.
On a Ping i see the radio respond.
Cant connect the radio tcp poort

**Comment by NoobishSVK** [comment]
Hello, which version of the tuner are you using? 
Don't forget that currently you can only assign a static IP to the tuner (that will be modified in the future). Have you tried setting one? That might just be the issue, try assigning a free IP somewhere in the 192.168.178.x network subnet. 

Please let me know if that works for you.

**Comment by laarhoven1** [comment]
problem fixed the isue is i try to connect the port.
(Set the TCP/IP Port to 7376 (or other specified in XDR-GTK settings).
but i find out with older versions of XDR-GTK the default port is 7373 and not (7376 ) as the webpage is given of XDR-GTK 
after set to 7373 the radio connect to Wifi and de wifi antenna symbol get white !
fixed.
